import type { Metadata } from "next";
// import DashboardLayout from "@/components/layouts/dashboard-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return <DashboardLayout>{children}</DashboardLayout>;
  return <div>{children}</div>;
}
